#!/bin/bash

##
#	Bash script to download Postgres SQL log from RDS and upload to S3 bucket
##

INSTANCE=rds-db-identifier
mkdir -p ${INSTANCE} && cd ${INSTANCE}
for i in `aws rds describe-db-log-files --db-instance-identifier ${INSTANCE} --output text | awk '{print $3}' | sed '$d' | tail -n 3` ; do
	FILE=`basename ${i}`
	ARCHIVE=${FILE}.tar.gz
	BUCKET='backup-db-log'
	if [ ! -e ${ARCHIVE} ]; then
		echo "Downloading ${i} ........."
		aws rds download-db-log-file-portion --db-instance-identifier ${INSTANCE} --log-file-name ${i} --starting-token 0 --output text > ${FILE}
		tar -cvzf ${ARCHIVE} ${FILE}
		echo "Uploading to S3 bucket ........"
		aws s3 mv ${ARCHIVE} s3://${BUCKET}
		rm ${FILE}
	fi
done

